[package]
name = "lenia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
rand = "0.8.5"
colorgrad = "0.6.1"
fft2d = "0.1.0"
num-complex = "0.4.2"
